### ISSUE TITLE
Add count to entity list tabs component

### ISSUE THREAD

**Issue by frano-m** [clevercanary/data-explorer#108]
The `Tabs` component needs to be able to render a count. See the tabs in the [mocks](https://www.figma.com/file/U9jPm603kykMXxie8JNP0I/ALTOS-Data-Broswser?node-id=306-2069&t=x3lSKnOyOtR5yYlA-4) e.g. `Projects (237)`, `Samples (11.4k)`, and `Files (466.5k)`.

### Approach
- Add an optional `count` prop to Tab interface, typed "string".
- Add the (optional) count to the render of the Tab on line 40 of the [Tabs](https://github.com/clevercanary/data-explorer/blob/263afbd4982d8bdf920ffc89bf79037383a71828/packages/data-explorer-ui/src/components/common/Tabs/tabs.tsx#L40) component.
- Add `()` around the count value.

### DOD
- The tab's count, if defined, should render on the tab as `Tab Name (count)` and if not defined,  as `Tab Name`.

**Comment by NoopDog** [comment]
Complete
