### ISSUE TITLE
Create text button component

### ISSUE THREAD

**Issue by frano-m** [clevercanary/data-explorer#139]
Create a new text button component and corresponding story that will inherit font styles and colour from the parent component to match the "call to action" button in the Banner [mocks](https://www.figma.com/file/U9jPm603kykMXxie8JNP0I/ALTOS-Data-Broswser?type=design&node-id=1-4432&t=yAJ4BQEKyq6fgRBm-4).

### Approach

- Depends on https://github.com/clevercanary/data-explorer/issues/89.

#### Part A

- Create a new component `TextButton` in a new directory called `TextButton` under `packages/data-explorer-ui/src/components/common/Button/components`.
- Add `TextButtonProps` interface, comprising of the following:
  - children - ReactNode, required.
- Create a styled component to add styles to the TextButton component.
  - The styled component should be a styled Mui `ButtonBase`.
  - All font styles should be inherited.
  - The colour should be inherited.
  - Add `text-decoration: underline` and `vertical-align: unset` styles.

#### Part B

- Create a storybook with a single story for the new component.
- Let the story render the button as is, without passing any styles in, or creating a parent wrapper.

#### Part C

- Delete `TextButtonWhite` from `packages/data-explorer-ui/src/components/common/Button/button.styles.ts`.
- Delete `TextButtonWhiteTemplate` and `TextButtonWhiteStory` from `packages/data-explorer-ui/src/components/common/Button/button.stories.tsx`.
- Update the new `Banner` component story `BannerStory` from `packages/data-explorer-ui/src/components/common/Banner/banner.stories.tsx` argument `ButtonElType` to be the new `TextButton` story.

**Comment by MillenniumFalconMechanic** [comment]
Obsolete.
