### ISSUE TITLE
Update CallToActionButton story to use the latest storybook Meta and StoryObj functions

### ISSUE THREAD

**Issue by frano-m** [clevercanary/data-explorer#140]
### Approach

- Update the CallToActionButton story to use the latest storybook functions `Meta` and `StoryObj`.
- Remove `CallToActionButtonWithCustomComponentStory` as we can override the `CallToActionButtonStory` with arguments if we need to (for reuse).
- Remove `className` from `CallToActionButtonStory`.

**Comment by MillenniumFalconMechanic** [comment]
Obsolete.
