### ISSUE TITLE
Create new code component

### ISSUE THREAD

**Issue by frano-m** [clevercanary/data-explorer#162]
Create a new code component and story that displays as per [mock](https://www.figma.com/file/JOUDXkKfgivRNFdBsWDPEH/AnVIL-Data-Explorer?type=design&node-id=1012-16977&t=ef8sXufKEe9WDiXn-4).

<img width="1098" alt="image" src="https://user-images.githubusercontent.com/18710366/236097385-b8d44ee7-c3c9-4e02-9a5f-82df3d6a0f24.png">

### Approach

- Create a new component Code in a new directory `Code` under packages/data-explorer-ui/src/components/common.
- Add `CodeProps` interface, comprising of the following:
  - children - ReactNode, required.
- Create a styled component to style the "code" text only.
  - Out of scope styles include:
    - the blue background, and
    - the padding around the text,
    - any hover related styles.
- Update, if required, storybook's `preview-head.html` file in `packages/data-explorer-ui/.storybook/preview-head.html` with "Roboto Mono"
- Create a new story for the new component.
- Out of scope:
  - Do not update or use the typography theme.
  - Do not add any copy to clipboard action.

**Comment by MillenniumFalconMechanic** [comment]
Obsolete.
