### ISSUE TITLE
Update code component to copy to clipboard

### ISSUE THREAD

**Issue by frano-m** [clevercanary/data-explorer#168]
Using the component `Code`, update the component to match the mocks [here](https://www.figma.com/file/JOUDXkKfgivRNFdBsWDPEH/AnVIL-Data-Explorer?type=design&node-id=1012-17191&t=H3Mlc634huwDw1VJ-4) and [here](https://www.figma.com/file/JOUDXkKfgivRNFdBsWDPEH/AnVIL-Data-Explorer?type=design&node-id=790-12508&t=xxkqUJa9QWvYH5Qj-4) and [here](https://www.figma.com/file/JOUDXkKfgivRNFdBsWDPEH/AnVIL-Data-Explorer?type=design&node-id=4312-35808&t=xxkqUJa9QWvYH5Qj-4). Add a copy to clipboard action to the component.

### Approach

Depends on #162 

- Add to `CodeBlock` styles with padding and colour and any other styles (border/radius etc) to match [mocks](https://www.figma.com/file/JOUDXkKfgivRNFdBsWDPEH/AnVIL-Data-Explorer?type=design&node-id=1012-17191&t=H3Mlc634huwDw1VJ-4).
- Refactor the prop name `children` to `code`, required, "string".
- Add onClick to the `CodeBlock` and use the existing `import copy from "copy-to-clipboard"` to copy the prop "code".
- Add appropriate cursor styles to the clickable area and hover/action/response styles.

- Add an additional CodeBlockWhite to `packages/data-explorer-ui/src/components/common/Code/code.styles.ts`, styled from `CodeBlock` and change the background colour to white.

**Comment by MillenniumFalconMechanic** [comment]
Obsolete.
