### ISSUE TITLE
Update Tab theme styles with hover state

### ISSUE THREAD

**Issue by frano-m** [clevercanary/data-explorer#178]
Update the Tab theme hover state to match the [mock](https://www.figma.com/file/JOUDXkKfgivRNFdBsWDPEH/AnVIL-Data-Explorer?type=design&node-id=1012-21029&t=xxkqUJa9QWvYH5Qj-4).

### Approach

Update the [Tab theme](https://github.com/clevercanary/data-explorer/blob/41cd7996f32803148412c1a2cdf1a74691697e96/packages/data-explorer-ui/src/theme/common/components.ts#L1003) to match the mock **hover state only**.

Confirm via the Tabs story, that active and passive styles match the mock - discuss with @frano-m if they are different in any way.

### Definition of Done

Tab hover state should match the [mock](https://www.figma.com/file/JOUDXkKfgivRNFdBsWDPEH/AnVIL-Data-Explorer?type=design&node-id=1012-21029&t=xxkqUJa9QWvYH5Qj-4).

**Comment by MillenniumFalconMechanic** [comment]
Obsolete.
