### ISSUE TITLE
[Findable] Summary count component

### ISSUE THREAD

**Issue by MillenniumFalconMechanic** [clevercanary/data-explorer#198]
#### Approach
* Create summary count component as per [mocks](https://www.figma.com/file/i4uZsYkKAML9ivi2TIo6ug/HCA-Data-Explorer?type=design&node-id=3787-29464&t=tgrYUxBHmTnhAYAl-0): 
<img width="313" alt="Screen Shot 2023-06-20 at 11 04 33 AM" src="https://github.com/clevercanary/data-explorer/assets/2446424/c31d2358-04cb-4c0a-a926-16e1c0cc8816">

**Comment by frano-m** [comment]
Not required - component can be rendered using existing KeyValuePairs component.
