### ISSUE TITLE
Add fetchEntityDetail to server side fetch, client side filtering entity service

### ISSUE THREAD

**Issue by frano-m** [clevercanary/data-explorer#593]
The entity detail page needs to be able to fetch data, when authenticated, for the explore mode "server side fetch / client side filtering". Currently we are only able to fetch data for explore mode "service side fetch and filtering".

The [EntityDetailView](https://github.com/clevercanary/data-explorer/blob/a66463c64340f0554a7d95f20c427d28fa691e54/packages/data-explorer-ui/src/views/EntityDetailView/entityDetailView.tsx) component uses the hook [useFetchEntity](https://github.com/clevercanary/data-explorer/blob/a66463c64340f0554a7d95f20c427d28fa691e54/packages/data-explorer-ui/src/hooks/useFetchEntity.tsx) to return entity data. `fetchEntityDetail` is called from [here](https://github.com/clevercanary/data-explorer/blob/main/packages/data-explorer-ui/src/hooks/useFetchEntity.tsx#L51) when there is no data, or the user is logged in.

1. Update the `fetchEntityDetail` [service](https://github.com/clevercanary/data-explorer/blob/13d47b3a1b4c3d403667e10ecfd92226d125e891/packages/data-explorer-ui/src/entity/apicf/service.ts#L64) for explore mode `SS_FETCH_CS_FILTERING` to fetch the data, with a token.
2. Optionally use `entityMapper` to map the fetched data (see [here](https://github.com/clevercanary/data-explorer/blob/13d47b3a1b4c3d403667e10ecfd92226d125e891/packages/data-explorer-ui/src/entity/apicf/service.ts#L57)).
3. See `fetchEntityDetail` [model](https://github.com/clevercanary/data-explorer/blob/a66463c64340f0554a7d95f20c427d28fa691e54/packages/data-explorer-ui/src/entity/service/model.ts#L40) for reference.

**Comment by NoopDog** [comment]
Not required
