### ISSUE TITLE
Fix dependabot secuirty warnings

### ISSUE THREAD

**Issue by NoopDog** [clevercanary/data-explorer#79]
See:

https://github.com/clevercanary/data-explorer/security/dependabot

Can you determine what package is including the package generating the warning and try to bump the version of that?

I am not sure but I can be convinced that we should start bumping the package-lock versions of dependencies of dependencies.

**Comment by BruceRodrigues** [comment]
This PR https://github.com/clevercanary/data-explorer/pull/92/files should fix all vulnerabilities

**Comment by NoopDog** [comment]
Thanks Bruce!
