### ISSUE TITLE
Add story for CallToAction component

### ISSUE THREAD

**Issue by frano-m** [clevercanary/data-explorer#90]
https://github.com/clevercanary/data-explorer/tree/main/packages/data-explorer-ui/src/components/common/CopyToClipboard

**Comment by imadx** [comment]
> https://github.com/clevercanary/data-explorer/tree/main/packages/data-explorer-ui/src/components/common/CopyToClipboard


Hey @frano-m, the link in the description would be https://github.com/clevercanary/data-explorer/tree/main/packages/data-explorer-ui/src/components/common/Button/components/CallToActionButton/callToActionButton.tsx, yeah?
